settings:
  debug: false
# Those messages are null safe so if they can't be read the plugin would use default ones automatically.
message:
  invalid-placeholder: '&cINVALID PLACEHOLDER'
  invalid-kit: '&cKIT DOESN''T EXIST'
  invalid-party: '&cINVALID PARTY'
  party-member:
    # kept it empty so it doesnt appear when it's requested
    invalid:-player: ''
